In [2]:
print(7**4)

2401


In [7]:
 x = 'Hi there me!'
 print(x.split())   

['Hi', 'there', 'me!']


In [10]:
planet = 'Earth'
diameter = 12742
print("The diameter of Earth is {one} Kilometer ".format(one=diameter))

The diameter of Earth is 12742 Kilometer 


In [14]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
# find the index or output hello
lst[3][1][2][0]

'hello'

In [21]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
# find hello word;
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [29]:
def count(str):
    co=0
    for word in str.lower().split():
        if word == 'dog':
            co+=1
            
    return co

In [30]:
count('The dog runs very fast')

1

In [38]:
seq = ['soup','dog','salad','cat','great']
list(filter(lambda var:var[0]=='s',seq))




['soup', 'salad']

# Final Problem
**You are driving a little too fast, and a police officer stops you. Write a function
  to return one of 3 possible results: "No ticket", "Small ticket", or "Big Ticket". 
  If your speed is 60 or less, the result is "No Ticket". If speed is between 61 
  and 80 inclusive, the result is "Small Ticket". If speed is 81 or more, the result is "Big    Ticket". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all 
  cases. **

In [43]:
def speeds(speed,BDY):
    if BDY:
        Speeding = speed + 5
    else:
        speeding = speed
        
    if speed <=60 :
        print("NO ticket")
    elif speed < 81:
        print("Small Ticket")
    else:
        print("Big ticket")

In [44]:
speeds(81,True)

Big ticket


In [2]:
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
print("Max of Array :{}".format(arr.max()))
print("Min of Array :{}".format(arr.min()))


Max of Array :10
Min of Array :1


In [9]:
arr.dtype

dtype('int32')

In [17]:
import numpy as np
arr = np.zeros(10)
arr


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:

arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
arr =np.array([5,5,5,5,5,5,5,5,5,5])
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [25]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [26]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [32]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr = np.eye(3)
arr


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr = np.random.rand(2)
arr


array([0.32680765, 0.21388179])

In [1]:
abc = lambda x,y: x**y
abc(2,3)

8

In [2]:
#  map(func,seq)
x = [2,4,6,8]
xy = map(lambda x: x**2,x)
print(list(xy))

[4, 16, 36, 64]


In [5]:
import seaborn as sns 
kashti = sns.load_dataset('titanic')
kashti.to_csv('kashti.csv')
# online loading data in csv file

In [6]:
word = 'Zealand'
it = iter(word)
next(it)

'Z'

In [7]:
next(it)

'e'

In [8]:
next(it)

'a'

In [9]:
next(it)

'l'

In [10]:
next(it)

'a'

In [11]:
next(it)

'n'

In [12]:
next(it)
# next will print one by one 

'd'

In [16]:
words = 'DataCamp'
its = iter(words)
#  iterate will iterate the var
print(*its)
# * will print whole string

D a t a C a m p


In [17]:
level = ['Meet','me','soon','please']
e = list(enumerate(level))
print(e)

[(0, 'Meet'), (1, 'me'), (2, 'soon'), (3, 'please')]


In [18]:
a = ['1','2','3','4']
b = ['a','b','c','d']
c = list(zip(a,b))
c

[('1', 'a'), ('2', 'b'), ('3', 'c'), ('4', 'd')]

In [1]:
#  Reading of the file 
# file_name = 'anesh.txt'
file = open('anesh.txt', mode='r')
text = file.read()
file.close()
print(text)

My name is Anesh kumar 


In [2]:
# Writting in the file 
# file_name = 'anesh.txt'
file = open('anesh.txt', mode='w')
file.close()

In [5]:
with open('anesh.txt', 'r') as f:
    print(f.read())


In [ ]:
# pd.ExcelFile()

# Import sas7bdat package
#from sas7bdat import SAS7BDAT

# Save file to a DataFrame: df_sas
#with SAS7BDAT('sales.sas7bdat') as file:
#   df_sas = file.to_data_frame()

# Print head of DataFrame
#print(df_sas.head())

# Plot histograms of a DataFrame feature (pandas and pyplot already imported)
#pd.DataFrame.hist(df_sas[['P']])
#plt.ylabel('count')
#plt.show()

In [ ]:
# Import pandas
#import pandas as pd

# Load Stata file into a pandas DataFrame: df
#df = pd.read_stata('disarea.dta')

# Print the head of the DataFrame df
#print(df.head())

# Plot histogram of one column of the DataFrame
#pd.DataFrame.hist(df[['disa10']])
#plt.xlabel('Extent of disease')
#plt.ylabel('Number of countries')
#plt.show()

In [ ]:
# Import packages
#import numpy as np
#import h5py

# Assign filename: file
#file = 'LIGO_data.hdf5'

# Load file: data
#data = h5py.File(file, 'r')

# Print the datatype of the loaded file
#print(type(data))

# Print the keys of the file
#for key in data.keys():
#   print(key)


In [ ]:
# import MATLAB 
# Matrix laboratory
#scipy.io.loadmat() ---> read files
#scipy.io.savemat() ---> write files

# Import packag#e
#import scipy.io

# Load MATLAB file: mat
#mat = scipy.io.loadmat('albeck_gene_expression.mat')

# Print the datatype type of mat
#print(type(mat))


In [ ]:
# Import necessary module
#from sqlalchemy import create_engine

# Create engine: engine
#engine = create_engine('sqlite:///Chinook.sqlite')

# Save the table names to a list: table_names
#table_names = engine.table_names()

# Print the table names to the shell
#print(table_names)


In [ ]:
# Import packages
#from sqlalchemy import create_engine
#import pandas as pd

# Create engine: engine
#engine = create_engine('sqlite:///Chinook.sqlite')

# Open engine connection
#con = engine.connect()

# Perform query: rs
#rs = con.execute("SELECT * FROM Album")

# Save results of the query to DataFrame: df
#df = pd.DataFrame(rs.fetchall())

# Close connection
#con.close()

# Print head of DataFrame df
#print(df.head())


In [ ]:
# Import packages
#from sqlalchemy import create_engine
#import pandas as pd

# Create engine: engine
#engine = create_engine('sqlite:///Chinook.sqlite')

# Execute query and store records in DataFrame: df
#df = pd.read_sql_query("SELECT * FROM Album", engine)

# Print head of DataFrame
#print(df.head())



In [ ]:
# Import package
#from urllib.request import urlretrieve

# Import pandas
# import pandas as 

# Assign url of file: url
#url = 'https://assets.datacamp.com/production/course_1606/datasets/winequality-red.csv'

# Save file locally
#urlretrieve(url, 'winequality-red.csv')

# Read file into a DataFrame and print its head
#df = pd.read_csv('winequality-red.csv', sep=';')
#print(df.head())

In [6]:
# URL
# uniform/universal resource locator focus on web resources
# HTTP
# Hypertext transfer protocol 
# HTTPS secure form of HTTP

# Import packages
#from urllib.request import urlopen, Request

# Specify the url
#url = "https://campus.datacamp.com/courses/1606/4135?ex=2"

# This packages the request: request
#request = Request(url)

# Sends the request and catches the response: response
#response = urlopen(request)

# Print the datatype of response
#print(type(response))

# Be polite and close the response!
#response.close()



In [ ]:
# API ----> Application programming interface , building and interacting of software application
# JSON ---> Javascript object notation real time server to browser communication