## NUMPY
- Package for Scientific Computing
- Great for big numerical operations
- Prove multidimensional array object ,various denied objects 
- Consumes less memory , fast and efficient way to create numpy 
- list contain hetrogenous members while array contains homogenous members


In [1]:
5+5

10

In [2]:
6**2

36

In [3]:
a=5
b=3
c=a+b
c

8

ARRAY

In [7]:
import numpy as np
x = np.array([1,2,3])
print(x)
print(type(x))
print(x.dtype)
print(x.ndim)
# ndim -------> for checking * Dimensional *  
# 1-d array is called vector eg assembly line 

[1 2 3]
<class 'numpy.ndarray'>
int32
1


In [8]:
import numpy as np  
x = np.array([[1,2,3],['a','b','c']])
print(x)
print(type(x))
print(x.dtype)
print(x.ndim)
# ndim -------> for checking * Dimensional *

[['1' '2' '3']
 ['a' 'b' 'c']]
<class 'numpy.ndarray'>
<U11
2


In [6]:
import numpy as np  
x = np.array([[[1,2,3],
                ['a','b','c'],
              [4,5,6]],
              
              [[5,6,7],
               ['d','e','f'],
              [8,9,0]]])
print(x)
print(type(x))
print(x.ndim)
print(x.dtype)
print(x.shape) 
# ndim -------> for checking * Dimensional *  
# more than 2D is called tensor flow for AI , ML 

[[['1' '2' '3']
  ['a' 'b' 'c']
  ['4' '5' '6']]

 [['5' '6' '7']
  ['d' 'e' 'f']
  ['8' '9' '0']]]
<class 'numpy.ndarray'>
3
<U11
(2, 3, 3)


In [6]:
# list
x = [1,2,3]
print(x)

[1, 2, 3]


In [11]:
import numpy as anesh
x=anesh.arange(4)
y=anesh.arange(4,8)
z=anesh.arange(4,10,2)
print(x)
print(y)
print(z)

[0 1 2 3]
[4 5 6 7]
[4 6 8]


In [13]:
a=np.array([1,2],ndmin=10)
print(a)

[[[[[[[[[[1 2]]]]]]]]]]


### Statistical operation with array

In [8]:
print(y.mean())
print(y.argmax())
print(y.argsort())
print(y.cumsum())

1.5
3
[0 1 2 3]
[0 1 3 6]


In [9]:
y=np.arange(2,4)
y

array([2, 3])

In [10]:
y=np.arange(2,9,2)
y


array([2, 4, 6, 8])

In [11]:
l=[]
for i in range(1,5):
    int_1=int(input("Enter value : "))
    l.append(int_1)
    
print(np.array(l))    
    

Enter value : 2
Enter value : 2
Enter value : 2
Enter value : 2
[2 2 2 2]


N-Dimensional Array

In [12]:
y = np.array([[1,2,3,4],[1,2,3,4]])
print(y)
print(y.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [13]:

a = np.array([1,2,3,4], ndmin=10)
print(a)
print(a.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


Zeros Array

In [14]:
zeros_1 = np.zeros(4)
zeros_2 = np.zeros((2,3))
Empty_3 = np.empty(3) 
print(zeros_1)
print()
print(zeros_2)
print()
print(Empty_3)



[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[1.48553242e-311 0.00000000e+000 1.33511969e-306]


Ones Array

In [15]:
ones_1 = np.ones(4,dtype=np.int8)
# dtype used for data type 
ones_2 = np.ones((2,3))
print(ones_1)
print()
print(ones_2)

[1 1 1 1]

[[1. 1. 1.]
 [1. 1. 1.]]


Empty Arrray

In [14]:
Emty_arr = np.empty(4)
print(Emty_arr)

[1.17741390e-311 1.17743358e-311 1.17743358e-311 1.17743489e-311]


Range

In [15]:
narr = np.arange(4)
print(narr)

[0 1 2 3]


In [17]:
array=np.random.randint(0,10, size=(3,5))
array
#  return int from 0,10

array([[5, 1, 1, 8, 9],
       [4, 9, 2, 9, 6],
       [5, 2, 2, 0, 6]])

In [21]:
np.random.seed(7) # used for unchange 
array1=np.random.rand(4)
array1
# float from 0 to 1

array([0.07630829, 0.77991879, 0.43840923, 0.72346518])

In [33]:
c=np.array([1,2,3,4])
d=np.array([2,4,6,8])
print(c+d)
print(np.add(c,d))
print(c-d)
print(np.subtract(c,d))
print(c*d)
print(np.multiply(c,d))
print(c/d)
print(np.divide(c,d))
print(c**d)
print(np.square(c,d))
print(c//d) # floor division

[ 3  6  9 12]
[ 3  6  9 12]
[-1 -2 -3 -4]
[-1 -2 -3 -4]
[ 2  8 18 32]
[ 2  8 18 32]
[0.5 0.5 0.5 0.5]
[0.5 0.5 0.5 0.5]
[    1    16   729 65536]
[ 1  4  9 16]
[1 0 0 0]


In [36]:
l=[1,2,3]
print(sum(l))
%timeit sum(l) 
print(np.sum(l))
%timeit np.sum(l)

6
225 ns ± 1.73 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
6
9.06 µs ± 226 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [43]:
length=[ 6, 7,10, 12, 13, 4, 8, 12]
x =np.mean(length)
print(x)
y=np.var(length)
print(y)
z=np.sqrt(y)
print(z)

9.0
9.25
3.0413812651491097


## Array Functions

In [23]:
import numpy as np
x = np.array([2,3,1,56,8,9])
y = np.array([2,3,1,12,22,34])

In [22]:
z = np.concatenate((x,y))
# z output of z is array([ 2,  3,  1, 56,  8,  9,  2,  3,  1, 12, 22, 34])
z.sort()
z

array([0, 1, 2, 3, 4, 5, 6, 7])

Diagonal

In [26]:
Diagonal = np.eye(3)
print(Diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Linspace

In [27]:
lin = np.linspace(0,20,num=5)
print(lin)

[ 0.  5. 10. 15. 20.]


In [28]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [37]:
a = np.arange(9)
# a.reshape(3,3) output of this
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])
np.reshape(a,newshape=(3,3),order='F')
# order: C means to read/write the elements using C-like index order, F means to read/write 
#        the elements using Fortran-like index order,A means to read/write the elements in 
#        Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. 
#        (This is an optional parameter and doesn’t need to be specified.)  

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [38]:
a1 = np.array([[1, 1],[ 2, 2]])
a2 = np.array([[3, 3],[4, 4]])
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [39]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [42]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))

[11 12 13 14 15 16 17 18 19 20]


In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [59]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a1 = x.flatten()
#  flatten change the multidimensional to 1D array
# But can't chanmge parent array
a1[0]=98
x


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a1

array([98,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c = b.ravel()
c[0]=98
#   ravel() change the multidimensional to 1D array
#   But change parent Array 
b

array([[98,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
c

array([98,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#  rand

In [63]:
b = np.random.rand(5)
print(b)
# create array b/w 0 and 1

[0.61429424 0.37391895 0.92535446 0.57542742 0.82353557]


#  randn

In [64]:
c = np.random.randn(5)
print(c)
#create array closely zero as (-ve,+ve)

[ 0.85346096  0.66279645 -0.41799205 -0.67737462  0.17068726]


#  ranf

In [65]:
d = np.random.ranf(5)
print(d)
# random sampling

[0.71478298 0.09955261 0.32651776 0.45815021 0.88106027]


#  randint

In [66]:
e = np.random.randint(5,20,5)
print(e)
# (min,max,step)
# create @ given range 

[ 7 11  9  9  9]


#  **DATA TYPE**

In [2]:
ad = np.array([1,2,3,4,565,6])
print(ad.dtype)

int32


Arthematic 

In [3]:
ab = np.array([1,2,3,4])
ss = ab - 3
print(ss)

[-2 -1  0  1]


In [4]:
ab = np.array([1,2,3,4])
ac = np.array([2,3,4,5])
ad = np.add(ab,ac)
print(ad)

[3 5 7 9]


In [5]:
import numpy as  np
d = np.array([2,3,4,5,67,7,])
print("MIN :",np.min(d),np.argmin(d))
print("Max :",np.max(d),np.argmax(d))
print("Cummulative sum :",np.cumsum(d))
print("SinQ :",np.sin(90))
print("CosQ :",np.cos(180))


MIN : 2 0
Max : 67 4
Cummulative sum : [ 2  5  9 14 81 88]
SinQ : 0.8939966636005579
CosQ : -0.5984600690578582


In [6]:
b = np.array([[2,3,5,7],[2,1,4,57]])
print(np.min(b,axis=0))
# axis zero as col compare
print(np.min(b,axis=1))

[2 1 4 7]
[2 1]


#  Search

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,876,5,4,5])
y = np.where(x == 5)
print(y)

In [7]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,876,5,4,5])
y = np.sort(x)
print(y)

[  1   2   3   4   4   5   5   5   6   7 876]


#  Matrix 

In [8]:
import numpy as np
x = np.matrix([[1,3],[2,4]])
y = np.matrix([[1,3],[2,4]])
print(x+y)


[[2 6]
 [4 8]]


#    Multiplication

In [9]:
import numpy as np
x = np.matrix([[1,3],[2,4]])
y = np.matrix([[1,3],[2,4]])
print(x.dot(y))

[[ 7 15]
 [10 22]]


#  Transpore

In [11]:
import numpy as np
x = np.matrix([[1,3],[2,4],[34,35]])
print(np.transpose(x))

[[ 1  2 34]
 [ 3  4 35]]


#  Inverse of matrix

In [12]:
import numpy as np
x = np.matrix([[1,3],[2,4]])
print(np.linalg.inv(x))

[[-2.   1.5]
 [ 1.  -0.5]]


#  Power of Matrix

In [13]:
import numpy as np
x = np.matrix([[1,3],[2,4]])
print(np.linalg.matrix_power(x,2))

[[ 7 15]
 [10 22]]


# Determinate OF THE MATRIX

In [14]:
import numpy as np
x = np.matrix([[1,3],[2,4]])
print(np.linalg.det(x))

-2.0


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 4,-1)
print(newarr)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [75]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
